#!/usr/bin/env python3
"""Fail-closed validation for every artifact generated by ``just icons``."""

from __future__ import annotations

import json
from pathlib import Path
import struct
import sys
import zlib


SLOTS = tuple((size, scale) for size in (16, 32, 128, 256, 512) for scale in (1, 2))
MAX_PNG_BYTES = 16 * 1024 * 1024
MAX_ICNS_BYTES = 16 * 1024 * 1024
MAX_JSON_BYTES = 128 * 1024
MINIMUM_PEAK_ALPHA = 64
MINIMUM_OPAQUE_EQUIVALENT_DIVISOR = 20


class ValidationFailure(Exception):
    pass


def paeth_predictor(left: int, above: int, upper_left: int) -> int:
    estimate = left + above - upper_left
    left_distance = abs(estimate - left)
    above_distance = abs(estimate - above)
    upper_left_distance = abs(estimate - upper_left)
    if left_distance <= above_distance and left_distance <= upper_left_distance:
        return left
    if above_distance <= upper_left_distance:
        return above
    return upper_left


def unfilter_rgba8(
    decoded: bytes,
    width: int,
    height: int,
    label: str,
) -> bytes:
    """Reconstruct exact RGBA8 pixels from bounded, non-interlaced scanlines."""

    bytes_per_pixel = 4
    row_bytes = width * bytes_per_pixel
    encoded_stride = row_bytes + 1
    pixels = bytearray(row_bytes * height)

    for row_index in range(height):
        encoded_offset = row_index * encoded_stride
        filter_kind = decoded[encoded_offset]
        if filter_kind > 4:
            raise ValidationFailure(f"invalid PNG scanline filter: {label}")
        source = decoded[encoded_offset + 1 : encoded_offset + encoded_stride]
        destination_offset = row_index * row_bytes
        prior_offset = destination_offset - row_bytes
        for column, value in enumerate(source):
            left = (
                pixels[destination_offset + column - bytes_per_pixel]
                if column >= bytes_per_pixel
                else 0
            )
            above = pixels[prior_offset + column] if row_index else 0
            upper_left = (
                pixels[prior_offset + column - bytes_per_pixel]
                if row_index and column >= bytes_per_pixel
                else 0
            )
            if filter_kind == 0:
                predictor = 0
            elif filter_kind == 1:
                predictor = left
            elif filter_kind == 2:
                predictor = above
            elif filter_kind == 3:
                predictor = (left + above) // 2
            else:
                predictor = paeth_predictor(left, above, upper_left)
            pixels[destination_offset + column] = (value + predictor) & 0xFF
    return bytes(pixels)


def validate_visible_rgba8(pixels: bytes, label: str) -> None:
    """Reject structurally valid output that would render blank or uniform."""

    if not pixels or len(pixels) % 4:
        raise ValidationFailure(f"invalid decoded RGBA pixel inventory: {label}")
    pixel_count = len(pixels) // 4
    alpha_total = 0
    peak_alpha = 0
    first_rendered_pixel: tuple[int, int, int, int] | None = None
    has_visible_variation = False
    for offset in range(0, len(pixels), 4):
        red, green, blue, alpha = pixels[offset : offset + 4]
        alpha_total += alpha
        peak_alpha = max(peak_alpha, alpha)
        # Fully transparent RGB is not rendered and must not manufacture
        # apparent variation. Premultiplication also reflects what the icon
        # contributes visually rather than hidden source-channel noise.
        rendered = (
            red * alpha // 255,
            green * alpha // 255,
            blue * alpha // 255,
            alpha,
        )
        if first_rendered_pixel is None:
            first_rendered_pixel = rendered
        elif rendered != first_rendered_pixel:
            has_visible_variation = True

    minimum_alpha_total = max(
        255,
        pixel_count * 255 // MINIMUM_OPAQUE_EQUIVALENT_DIVISOR,
    )
    if peak_alpha < MINIMUM_PEAK_ALPHA or alpha_total < minimum_alpha_total:
        raise ValidationFailure(f"generated icon is visually empty: {label}")
    if not has_visible_variation:
        raise ValidationFailure(f"generated icon has no visible variation: {label}")


def decode_legacy_argb(payload: bytes, dimension: int, label: str) -> bytes:
    """Decode iconutil's bounded legacy per-channel ICNS run encoding."""

    if not payload.startswith(b"ARGB"):
        raise ValidationFailure(f"invalid legacy representation: {label}")
    pixel_count = dimension * dimension
    cursor = 4
    channels: list[bytes] = []
    for _ in range(4):
        channel = bytearray()
        while len(channel) < pixel_count:
            if cursor >= len(payload):
                raise ValidationFailure(f"truncated legacy representation: {label}")
            control = payload[cursor]
            cursor += 1
            if control >= 128:
                count = control - 125
                if cursor >= len(payload) or len(channel) + count > pixel_count:
                    raise ValidationFailure(f"invalid legacy representation: {label}")
                channel.extend((payload[cursor],) * count)
                cursor += 1
            else:
                count = control + 1
                end = cursor + count
                if end > len(payload) or len(channel) + count > pixel_count:
                    raise ValidationFailure(f"invalid legacy representation: {label}")
                channel.extend(payload[cursor:end])
                cursor = end
        channels.append(bytes(channel))
    if cursor != len(payload):
        raise ValidationFailure(f"trailing legacy representation data: {label}")

    alpha, red, green, blue = channels
    pixels = bytearray(pixel_count * 4)
    for index in range(pixel_count):
        destination = index * 4
        pixels[destination : destination + 4] = bytes(
            (red[index], green[index], blue[index], alpha[index])
        )
    return bytes(pixels)


def filename(size: int, scale: int) -> str:
    suffix = "" if scale == 1 else f"@{scale}x"
    return f"icon_{size}x{size}{suffix}.png"


def expected_images() -> list[dict[str, str]]:
    return [
        {
            "filename": filename(size, scale),
            "idiom": "mac",
            "scale": f"{scale}x",
            "size": f"{size}x{size}",
        }
        for size, scale in SLOTS
    ]


def require_directory(path: Path) -> None:
    if path.is_symlink() or not path.is_dir():
        raise ValidationFailure(f"missing generated directory: {path}")


def require_regular_file(path: Path) -> None:
    if path.is_symlink() or not path.is_file():
        raise ValidationFailure(f"missing generated file: {path}")


def validate_inventory(directory: Path, expected: set[str]) -> None:
    require_directory(directory)
    actual = {entry.name for entry in directory.iterdir()}
    missing = sorted(expected - actual)
    unexpected = sorted(actual - expected)
    if missing or unexpected:
        details = []
        if missing:
            details.append("missing " + ", ".join(missing))
        if unexpected:
            details.append("unexpected " + ", ".join(unexpected))
        raise ValidationFailure(f"invalid inventory in {directory}: {'; '.join(details)}")


def load_json(path: Path) -> object:
    require_regular_file(path)
    size = path.stat().st_size
    if size <= 0 or size > MAX_JSON_BYTES:
        raise ValidationFailure(f"invalid generated JSON size for {path}: {size}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValidationFailure(f"invalid generated JSON {path}: {error}") from error


def validate_png_data(
    data: bytes, label: str, expected_width: int, expected_height: int
) -> None:
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        raise ValidationFailure(f"invalid PNG signature: {label}")

    offset = 8
    dimensions: tuple[int, int] | None = None
    encoding: tuple[int, int, int, int, int] | None = None
    compressed = bytearray()
    saw_data = False
    idat_closed = False
    saw_end = False
    while offset < len(data):
        if len(data) - offset < 12:
            raise ValidationFailure(f"truncated PNG chunk: {label}")
        length = struct.unpack_from(">I", data, offset)[0]
        kind = data[offset + 4 : offset + 8]
        if (
            any(not (65 <= byte <= 90 or 97 <= byte <= 122) for byte in kind)
            or kind[2] & 0x20
        ):
            raise ValidationFailure(f"invalid PNG chunk type: {label}")
        if not kind[0] & 0x20 and kind not in {b"IHDR", b"PLTE", b"IDAT", b"IEND"}:
            raise ValidationFailure(
                f"unknown critical PNG chunk {kind.decode('ascii')}: {label}"
            )
        payload_start = offset + 8
        payload_end = payload_start + length
        checksum_end = payload_end + 4
        if checksum_end > len(data):
            raise ValidationFailure(f"truncated PNG chunk: {label}")
        expected_crc = struct.unpack_from(">I", data, payload_end)[0]
        actual_crc = zlib.crc32(kind + data[payload_start:payload_end]) & 0xFFFF_FFFF
        if actual_crc != expected_crc:
            raise ValidationFailure(f"invalid PNG checksum: {label}")

        if kind == b"IHDR":
            if dimensions is not None or offset != 8 or length != 13:
                raise ValidationFailure(f"invalid PNG header: {label}")
            header = struct.unpack_from(">IIBBBBB", data, payload_start)
            dimensions = header[:2]
            encoding = header[2:]
        elif kind == b"IDAT":
            if dimensions is None or idat_closed:
                raise ValidationFailure(f"invalid PNG data ordering: {label}")
            saw_data = True
            compressed.extend(data[payload_start:payload_end])
            if len(compressed) > MAX_PNG_BYTES:
                raise ValidationFailure(f"compressed pixel stream is oversized: {label}")
        elif kind == b"IEND":
            if length != 0 or checksum_end != len(data):
                raise ValidationFailure(f"invalid PNG end marker: {label}")
            saw_end = True
            offset = checksum_end
            break
        elif saw_data:
            idat_closed = True
        offset = checksum_end

    if dimensions != (expected_width, expected_height):
        observed = "missing" if dimensions is None else f"{dimensions[0]}x{dimensions[1]}"
        raise ValidationFailure(
            f"{label} is {observed}; expected {expected_width}x{expected_height}"
        )
    if not saw_data or not saw_end or offset != len(data):
        raise ValidationFailure(f"incomplete PNG: {label}")
    if encoding != (8, 6, 0, 0, 0):
        raise ValidationFailure(
            f"unsupported generated PNG encoding {encoding}: {label}"
        )

    row_bytes = expected_width * 4
    expected_decoded_bytes = expected_height * (row_bytes + 1)
    decoder = zlib.decompressobj()
    try:
        decoded = decoder.decompress(
            bytes(compressed), expected_decoded_bytes + 1
        )
        if decoder.unconsumed_tail or len(decoded) > expected_decoded_bytes:
            raise ValidationFailure(f"compressed pixel stream is oversized: {label}")
        decoded += decoder.flush()
    except zlib.error as error:
        raise ValidationFailure(
            f"invalid compressed pixel stream: {label}: {error}"
        ) from error
    if (
        not decoder.eof
        or decoder.unused_data
        or decoder.unconsumed_tail
        or len(decoded) != expected_decoded_bytes
    ):
        raise ValidationFailure(f"invalid decoded pixel stream length: {label}")
    pixels = unfilter_rgba8(decoded, expected_width, expected_height, label)
    validate_visible_rgba8(pixels, label)


def validate_png(path: Path, expected_width: int, expected_height: int) -> None:
    require_regular_file(path)
    size = path.stat().st_size
    if size <= 0 or size > MAX_PNG_BYTES:
        raise ValidationFailure(f"invalid PNG size for {path}: {size}")
    validate_png_data(path.read_bytes(), path.name, expected_width, expected_height)


def validate_icns(path: Path) -> None:
    require_regular_file(path)
    size = path.stat().st_size
    if size <= 0 or size > MAX_ICNS_BYTES:
        raise ValidationFailure(
            f"DocumentIcon.icns exceeds its size safety limit: {path}: {size}"
        )
    data = path.read_bytes()
    if len(data) < 16 or data[:4] != b"icns":
        raise ValidationFailure(f"invalid DocumentIcon.icns header: {path}")
    declared = struct.unpack_from(">I", data, 4)[0]
    if declared != len(data):
        raise ValidationFailure(
            f"invalid DocumentIcon.icns length: declared {declared}, actual {len(data)}"
        )

    offset = 8
    chunks: dict[bytes, bytes] = {}
    while offset < len(data):
        if len(data) - offset < 8:
            raise ValidationFailure(f"truncated DocumentIcon.icns chunk: {path}")
        length = struct.unpack_from(">I", data, offset + 4)[0]
        if length < 8 or offset + length > len(data):
            raise ValidationFailure(f"invalid DocumentIcon.icns chunk length: {path}")
        kind = data[offset : offset + 4]
        if kind in chunks:
            raise ValidationFailure(
                f"duplicate DocumentIcon.icns representation: {kind.decode('latin1')}"
            )
        chunks[kind] = data[offset + 8 : offset + length]
        offset += length
    if offset != len(data) or not chunks:
        raise ValidationFailure(f"incomplete DocumentIcon.icns: {path}")

    # iconutil emits one representation per iconset slot. Types ic04/ic05 are
    # the specification's legacy 16/32px ARGB payloads; the remaining types
    # carry PNG data whose physical dimensions can be checked directly.
    expected = {
        b"ic04": 16,
        b"ic11": 32,
        b"ic05": 32,
        b"ic12": 64,
        b"ic07": 128,
        b"ic13": 256,
        b"ic08": 256,
        b"ic14": 512,
        b"ic09": 512,
        b"ic10": 1024,
    }
    missing = sorted(kind.decode("latin1") for kind in expected.keys() - chunks.keys())
    unexpected = sorted(
        kind.decode("latin1")
        for kind in chunks.keys() - expected.keys() - {b"TOC ", b"info"}
    )
    if missing or unexpected:
        details = []
        if missing:
            details.append("missing " + ", ".join(missing))
        if unexpected:
            details.append("unexpected " + ", ".join(unexpected))
        raise ValidationFailure("invalid DocumentIcon.icns inventory: " + "; ".join(details))

    for kind, dimension in expected.items():
        payload = chunks[kind]
        label = f"DocumentIcon.icns {kind.decode('latin1')}"
        if kind in {b"ic04", b"ic05"}:
            pixels = decode_legacy_argb(payload, dimension, label)
            validate_visible_rgba8(pixels, label)
        else:
            validate_png_data(payload, label, dimension, dimension)


def validate_freshness(outputs: list[Path], sources: list[Path]) -> None:
    if not sources:
        return
    for source in sources:
        require_regular_file(source)
    newest_source = max(source.stat().st_mtime_ns for source in sources)
    stale = [str(output) for output in outputs if output.stat().st_mtime_ns < newest_source]
    if stale:
        raise ValidationFailure("stale generated icon assets: " + ", ".join(stale))


def validate(catalog: Path, document: Path, sources: list[Path]) -> None:
    icon_set = catalog / "AppIcon.appiconset"
    root_manifest = catalog / "Contents.json"
    icon_manifest = icon_set / "Contents.json"
    names = {filename(size, scale) for size, scale in SLOTS}

    validate_inventory(catalog, {"Contents.json", "AppIcon.appiconset"})
    validate_inventory(icon_set, names | {"Contents.json"})

    expected_info = {"author": "icongen", "version": 1}
    if load_json(root_manifest) != {"info": expected_info}:
        raise ValidationFailure(f"generated catalogue metadata differs: {root_manifest}")
    expected_manifest = {"images": expected_images(), "info": expected_info}
    if load_json(icon_manifest) != expected_manifest:
        raise ValidationFailure(f"generated slot inventory differs: {icon_manifest}")

    outputs = [root_manifest, icon_manifest, document]
    for size, scale in SLOTS:
        path = icon_set / filename(size, scale)
        validate_png(path, size * scale, size * scale)
        outputs.append(path)
    validate_icns(document)
    validate_freshness(outputs, sources)


def main(arguments: list[str]) -> int:
    if len(arguments) < 2:
        print(
            "usage: validate.py <Assets.xcassets> <DocumentIcon.icns> [sources ...]",
            file=sys.stderr,
        )
        return 2
    try:
        validate(Path(arguments[0]), Path(arguments[1]), [Path(item) for item in arguments[2:]])
    except (OSError, ValidationFailure) as error:
        print(f"icons: validation failed: {error}", file=sys.stderr)
        return 1
    print("icons: generated catalogue validated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
