//! Safe, standalone HTML export.
//!
//! Raw HTML is valid CommonMark, but an exported note is commonly opened in a
//! browser where passing it through would turn note text into executable code.
//! This renderer deliberately treats raw HTML as text, rejects active URL
//! schemes, and adds a closed Content Security Policy around the rendered
//! fragment.

use std::borrow::Cow;
use std::collections::{HashMap, VecDeque};
use std::fs::File;
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};

use pulldown_cmark::{html, CowStr, Event, LinkType, Parser, Tag, TagEnd};

use crate::md::parse::options;

/// Rendering is linear but necessarily allocates output proportional to the
/// document. Refuse pathological inputs before duplicating them across the
/// Rust/Swift boundary.
pub const MAX_SOURCE_BYTES: usize = 16 * 1_048_576;
/// Titles normally come from a filesystem component (at most a few hundred
/// bytes), but the renderer is a public FFI boundary and must defend itself.
pub const MAX_TITLE_BYTES: usize = 8 * 1024;
const MAX_OUTPUT_BYTES: usize = 64 * 1024 * 1024;
/// The largest single local picture copied into an export. Matches the order
/// of magnitude the native renderer accepts for raster input.
pub const MAX_EMBEDDED_IMAGE_BYTES: usize = 8 * 1_048_576;
/// Total raw picture bytes one export may copy. Base64 grows this by a third,
/// which still leaves the text of the note well inside the output ceiling.
pub const MAX_EMBEDDED_TOTAL_BYTES: usize = 32 * 1_048_576;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HTMLExportError {
    SourceTooLarge { actual: usize, maximum: usize },
    TitleTooLarge { actual: usize, maximum: usize },
    OutputTooLarge { actual: usize, maximum: usize },
}

/// Optional behaviour for [`render_document_with_options`].
#[derive(Clone, Debug, Default)]
pub struct ExportOptions<'a> {
    /// The folder the note lives in. When set, local images referenced with
    /// Markdown image syntax are read, identified by their bytes, and copied
    /// into the document as `data:` URIs so the export opens correctly in any
    /// browser, from any location. Pictures that cannot be identified as a
    /// browser image format keep their original relative destination.
    pub asset_base: Option<&'a Path>,
}

/// Renders a complete browser-ready document from MarkDev's Markdown dialect.
pub fn render_document(source: &str, title: &str) -> Result<String, HTMLExportError> {
    render_document_with_options(source, title, &ExportOptions::default())
}

/// [`render_document`] with explicit export options.
pub fn render_document_with_options(
    source: &str,
    title: &str,
    export: &ExportOptions<'_>,
) -> Result<String, HTMLExportError> {
    if source.len() > MAX_SOURCE_BYTES {
        return Err(HTMLExportError::SourceTooLarge {
            actual: source.len(),
            maximum: MAX_SOURCE_BYTES,
        });
    }
    if title.len() > MAX_TITLE_BYTES {
        return Err(HTMLExportError::TitleTooLarge {
            actual: title.len(),
            maximum: MAX_TITLE_BYTES,
        });
    }

    // Keep output NUL-free even though Rust and Swift strings allow it. Avoid
    // copying the ordinary case; the replacement allocation is still bounded
    // by the source/title checks above.
    let clean_source: Cow<'_, str> = if source.contains('\0') {
        Cow::Owned(source.replace('\0', "\u{FFFD}"))
    } else {
        Cow::Borrowed(source)
    };
    let clean_title: Cow<'_, str> = if title.contains('\0') {
        Cow::Owned(title.replace('\0', "\u{FFFD}"))
    } else {
        Cow::Borrowed(title)
    };

    // Render straight into a writer that refuses the first byte beyond the
    // ceiling. Checking a String after `push_html` returns is too late: the
    // pathological allocation has already happened by then.
    let initial_capacity = clean_source
        .len()
        .saturating_add(clean_title.len())
        .saturating_add(8 * 1024)
        .min(MAX_OUTPUT_BYTES);
    let mut output = BoundedHTMLWriter::new(MAX_OUTPUT_BYTES, initial_capacity);
    output
        .write_all(DOCUMENT_PREFIX.as_bytes())
        .map_err(|_| output.error())?;
    html::write_html_io(
        &mut output,
        std::iter::once(Event::Text(CowStr::Borrowed(clean_title.as_ref()))),
    )
    .map_err(|_| output.error())?;
    output
        .write_all(DOCUMENT_MIDDLE.as_bytes())
        .map_err(|_| output.error())?;
    let events = ExportEvents::new(
        Parser::new_ext(clean_source.as_ref(), options()),
        ImageEmbedder::new(export.asset_base),
    );
    html::write_html_io(&mut output, events).map_err(|_| output.error())?;
    output
        .write_all(DOCUMENT_SUFFIX.as_bytes())
        .map_err(|_| output.error())?;

    // Every input to the writer is UTF-8 text generated by pulldown-cmark or
    // by this module's own ASCII markup.
    Ok(String::from_utf8(output.into_bytes()).expect("HTML writer emitted invalid UTF-8"))
}

/// A hard allocation boundary around pulldown-cmark's streaming renderer.
struct BoundedHTMLWriter {
    bytes: Vec<u8>,
    maximum: usize,
    attempted: usize,
}

impl BoundedHTMLWriter {
    fn new(maximum: usize, initial_capacity: usize) -> Self {
        Self {
            bytes: Vec::with_capacity(initial_capacity.min(maximum)),
            maximum,
            attempted: 0,
        }
    }

    fn error(&self) -> HTMLExportError {
        HTMLExportError::OutputTooLarge {
            actual: self.attempted.max(self.maximum.saturating_add(1)),
            maximum: self.maximum,
        }
    }

    fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }
}

impl Write for BoundedHTMLWriter {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        self.attempted = self.bytes.len().saturating_add(buffer.len());
        if self.attempted > self.maximum {
            return Err(io::Error::new(
                io::ErrorKind::FileTooLarge,
                "rendered HTML exceeds its byte limit",
            ));
        }
        self.bytes.extend_from_slice(buffer);
        Ok(buffer.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Streams parser events through sanitization, heading anchors, and image
/// embedding.
///
/// Headings are the only construct buffered: their `id` must be known when the
/// opening tag is written, and it is derived from the text inside. A heading is
/// a single block, so the buffer is bounded by the longest heading rather than
/// by the document.
struct ExportEvents<'a, I> {
    inner: I,
    pending: VecDeque<Event<'a>>,
    slugs: HashMap<String, usize>,
    images: ImageEmbedder<'a>,
}

impl<'a, I: Iterator<Item = Event<'a>>> ExportEvents<'a, I> {
    fn new(inner: I, images: ImageEmbedder<'a>) -> Self {
        Self {
            inner,
            pending: VecDeque::new(),
            slugs: HashMap::new(),
            images,
        }
    }

    fn unique_slug(&mut self, text: &str) -> String {
        let base = slugify(text);
        let base = if base.is_empty() {
            "section".to_owned()
        } else {
            base
        };
        let count = self.slugs.entry(base.clone()).or_insert(0);
        let slug = if *count == 0 {
            base.clone()
        } else {
            format!("{base}-{count}")
        };
        *count += 1;
        // Reserve the suffixed spelling too, so a later heading literally
        // titled "Intro 1" cannot collide with the second "Intro".
        if slug != base {
            self.slugs.entry(slug.clone()).or_insert(1);
        }
        slug
    }

    fn sanitize(&mut self, event: Event<'a>) -> Event<'a> {
        match event {
            // Preserve what the author typed, but never interpret it in the
            // browser. `push_html` escapes Text events for us.
            Event::Html(value) | Event::InlineHtml(value) => Event::Text(value),
            Event::Start(Tag::Link {
                link_type,
                dest_url,
                title,
                id,
            }) => {
                let dest_url = if matches!(link_type, LinkType::WikiLink { .. }) {
                    wikilink_destination(dest_url)
                } else {
                    sanitize_destination(dest_url, true, link_type)
                };
                Event::Start(Tag::Link {
                    dest_url,
                    link_type,
                    title,
                    id,
                })
            }
            Event::Start(Tag::Image {
                link_type,
                dest_url,
                title,
                id,
            }) => {
                // MarkDev's preview does not fetch remote images. Export keeps
                // the same privacy boundary rather than creating a browser
                // beacon; local pictures are copied in when a base is known.
                let dest_url = sanitize_destination(dest_url, false, link_type);
                let dest_url = match self.images.embed(&dest_url) {
                    Some(data) => CowStr::Boxed(data.into_boxed_str()),
                    None => dest_url,
                };
                Event::Start(Tag::Image {
                    link_type,
                    dest_url,
                    title,
                    id,
                })
            }
            other => other,
        }
    }
}

impl<'a, I: Iterator<Item = Event<'a>>> Iterator for ExportEvents<'a, I> {
    type Item = Event<'a>;

    fn next(&mut self) -> Option<Event<'a>> {
        if let Some(event) = self.pending.pop_front() {
            return Some(event);
        }
        match self.inner.next()? {
            Event::Start(Tag::Heading {
                level,
                id,
                classes,
                attrs,
            }) => {
                let mut text = String::new();
                let mut body = Vec::new();
                for event in self.inner.by_ref() {
                    match &event {
                        Event::End(TagEnd::Heading(_)) => break,
                        Event::Text(value) | Event::Code(value) => text.push_str(value),
                        _ => {}
                    }
                    body.push(event);
                }
                // Heading attributes are not enabled, so the parser never
                // supplies an id; derive one so in-page links resolve.
                let _ = id;
                let slug = self.unique_slug(&text);
                for event in body {
                    let event = self.sanitize(event);
                    self.pending.push_back(event);
                }
                // Slugs are built from alphanumerics, `-` and `_` only, so
                // they need no escaping inside the attribute.
                self.pending.push_back(Event::Html(CowStr::Boxed(
                    format!(
                        "<a class=\"anchor\" href=\"#{slug}\" aria-label=\"Link to this section\">#</a>"
                    )
                    .into_boxed_str(),
                )));
                self.pending.push_back(Event::End(TagEnd::Heading(level)));
                Some(Event::Start(Tag::Heading {
                    level,
                    id: Some(CowStr::Boxed(slug.into_boxed_str())),
                    classes,
                    attrs,
                }))
            }
            event => Some(self.sanitize(event)),
        }
    }
}
/// Wikilinks name a note, not a file. In a browser, point them at the Markdown
/// file beside the export and turn `#Heading` into the anchor this renderer
/// gives that heading, so `[[#Setup]]` navigates within the page.
fn wikilink_destination(destination: CowStr<'_>) -> CowStr<'_> {
    let (page, fragment) = match destination.split_once('#') {
        Some((page, fragment)) => (page, Some(fragment)),
        None => (destination.as_ref(), None),
    };
    let page = page.trim();
    let mut target = String::with_capacity(destination.len() + 8);
    if !page.is_empty() {
        let lower = page.to_ascii_lowercase();
        // A wikilink is always a note in the vault; never let it smuggle in
        // a scheme or a protocol-relative host.
        if lower.contains(':') || page.starts_with("//") {
            return CowStr::Borrowed("#");
        }
        for character in page.chars() {
            match character {
                ' ' => target.push_str("%20"),
                '"' => target.push_str("%22"),
                '?' => target.push_str("%3F"),
                _ => target.push(character),
            }
        }
        let has_extension = Path::new(page)
            .extension()
            .is_some_and(|extension| !extension.is_empty());
        if !has_extension {
            target.push_str(".md");
        }
    }
    if let Some(fragment) = fragment {
        let slug = slugify(fragment);
        if !slug.is_empty() {
            target.push('#');
            target.push_str(&slug);
        }
    }
    if target.is_empty() {
        CowStr::Borrowed("#")
    } else {
        CowStr::Boxed(target.into_boxed_str())
    }
}

/// GitHub-style heading slug: lowercase letters and digits, spaces become
/// hyphens, everything else is dropped.
pub fn slugify(text: &str) -> String {
    let mut slug = String::with_capacity(text.len());
    for character in text.trim().chars() {
        if character.is_alphanumeric() {
            slug.extend(character.to_lowercase());
        } else if character == ' ' || character == '-' {
            slug.push('-');
        } else if character == '_' {
            slug.push('_');
        }
    }
    slug
}

fn sanitize_destination<'a>(
    destination: CowStr<'a>,
    allow_remote: bool,
    link_type: LinkType,
) -> CowStr<'a> {
    if link_type == LinkType::Email {
        return destination;
    }

    let compact: String = destination
        .chars()
        .filter(|character| !character.is_ascii_control() && !character.is_ascii_whitespace())
        .collect();
    let lower = compact.to_ascii_lowercase();

    // Protocol-relative image URLs also perform a network request. Links may
    // navigate there only after an explicit click.
    if !allow_remote && lower.starts_with("//") {
        return CowStr::Borrowed("#");
    }

    let scheme = lower.find(':').and_then(|colon| {
        let boundary = lower.find(['/', '?', '#']).unwrap_or(usize::MAX);
        (colon < boundary).then_some(&lower[..colon])
    });

    let allowed = match scheme {
        None => true,
        Some("http" | "https") => allow_remote,
        Some("mailto" | "file") => true,
        _ => false,
    };
    if allowed {
        destination
    } else {
        CowStr::Borrowed("#")
    }
}

/// Copies local pictures into the export as `data:` URIs.
///
/// Only bytes that identify as a format browsers draw in `<img>` are copied,
/// and the MIME type comes from those bytes, never from the file name. An SVG
/// inside `<img>` cannot run script or load subresources, and the document's
/// Content-Security-Policy forbids both anyway.
struct ImageEmbedder<'a> {
    base: Option<&'a Path>,
    remaining: usize,
    cache: HashMap<PathBuf, Option<String>>,
}

impl<'a> ImageEmbedder<'a> {
    fn new(base: Option<&'a Path>) -> Self {
        Self {
            base,
            remaining: MAX_EMBEDDED_TOTAL_BYTES,
            cache: HashMap::new(),
        }
    }

    fn embed(&mut self, destination: &str) -> Option<String> {
        let base = self.base?;
        let path = local_image_path(destination, base)?;
        if let Some(cached) = self.cache.get(&path) {
            return cached.clone();
        }
        let embedded = self.load(&path);
        self.cache.insert(path, embedded.clone());
        embedded
    }

    fn load(&mut self, path: &Path) -> Option<String> {
        let limit = MAX_EMBEDDED_IMAGE_BYTES.min(self.remaining);
        let file = File::open(path).ok()?;
        let metadata = file.metadata().ok()?;
        if !metadata.is_file() || metadata.len() > limit as u64 {
            return None;
        }
        let mut bytes = Vec::with_capacity(metadata.len() as usize);
        // Read one byte past the limit so a file that grew after `metadata`
        // is refused rather than silently truncated.
        file.take(limit as u64 + 1).read_to_end(&mut bytes).ok()?;
        if bytes.len() > limit {
            return None;
        }
        let mime = sniff_image(&bytes)?;
        self.remaining -= bytes.len();
        let mut uri = String::with_capacity(bytes.len() / 3 * 4 + 64);
        uri.push_str("data:");
        uri.push_str(mime);
        uri.push_str(";base64,");
        base64_encode_into(&bytes, &mut uri);
        Some(uri)
    }
}

/// Resolves a Markdown image destination to a local file the way the native
/// renderer does: `file:` URLs, absolute paths, and paths relative to the
/// note's folder. Remote and directory destinations resolve to nothing.
fn local_image_path(destination: &str, base: &Path) -> Option<PathBuf> {
    let trimmed = destination.trim();
    if trimmed.is_empty() || trimmed == "#" {
        return None;
    }
    let decoded = percent_decode(trimmed)?;
    if decoded.starts_with("//") || decoded.ends_with('/') || decoded.contains('\0') {
        return None;
    }
    let lower = decoded.to_ascii_lowercase();
    if let Some(rest) = lower.strip_prefix("file:") {
        let offset = decoded.len() - rest.len();
        let rest = &decoded[offset..];
        let path = match rest.strip_prefix("//") {
            Some(authority_and_path) => {
                let slash = authority_and_path.find('/')?;
                let host = &authority_and_path[..slash];
                if !(host.is_empty() || host.eq_ignore_ascii_case("localhost")) {
                    return None;
                }
                &authority_and_path[slash..]
            }
            None => rest,
        };
        return Some(PathBuf::from(path));
    }
    let scheme_end = lower.find(':');
    let boundary = lower.find(['/', '?', '#']).unwrap_or(usize::MAX);
    if scheme_end.is_some_and(|colon| colon < boundary) {
        return None;
    }
    let path = Path::new(&decoded);
    if path.is_absolute() {
        Some(path.to_path_buf())
    } else {
        Some(base.join(path))
    }
}

fn percent_decode(value: &str) -> Option<String> {
    if !value.contains('%') {
        return Some(value.to_owned());
    }
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' && index + 2 < bytes.len() {
            let hex = std::str::from_utf8(&bytes[index + 1..index + 3]).ok()?;
            if let Ok(byte) = u8::from_str_radix(hex, 16) {
                decoded.push(byte);
                index += 3;
                continue;
            }
        }
        decoded.push(bytes[index]);
        index += 1;
    }
    String::from_utf8(decoded).ok()
}

/// The browser image format `bytes` identify as, if any.
pub fn sniff_image(bytes: &[u8]) -> Option<&'static str> {
    if bytes.starts_with(b"\x89PNG\r\n\x1a\n") {
        return Some("image/png");
    }
    if bytes.starts_with(&[0xFF, 0xD8, 0xFF]) {
        return Some("image/jpeg");
    }
    if bytes.starts_with(b"GIF87a") || bytes.starts_with(b"GIF89a") {
        return Some("image/gif");
    }
    if bytes.len() >= 12 && &bytes[..4] == b"RIFF" && &bytes[8..12] == b"WEBP" {
        return Some("image/webp");
    }
    if bytes.len() >= 12 && &bytes[4..8] == b"ftyp" {
        match &bytes[8..12] {
            b"avif" | b"avis" => return Some("image/avif"),
            _ => {}
        }
    }
    if bytes.starts_with(b"BM") && bytes.len() >= 26 {
        return Some("image/bmp");
    }
    if bytes.starts_with(&[0, 0, 1, 0]) && bytes.len() >= 22 {
        return Some("image/x-icon");
    }
    if looks_like_svg(bytes) {
        return Some("image/svg+xml");
    }
    None
}

/// An SVG document is UTF-8 XML whose root element is `svg`. Skip the prolog
/// (BOM, XML declaration, comments, doctype) and require that root.
fn looks_like_svg(bytes: &[u8]) -> bool {
    let Ok(text) = std::str::from_utf8(bytes) else {
        return false;
    };
    let mut rest = text.strip_prefix('\u{FEFF}').unwrap_or(text);
    loop {
        rest = rest.trim_start();
        if let Some(after) = rest.strip_prefix("<?") {
            let Some(end) = after.find("?>") else {
                return false;
            };
            rest = &after[end + 2..];
        } else if let Some(after) = rest.strip_prefix("<!--") {
            let Some(end) = after.find("-->") else {
                return false;
            };
            rest = &after[end + 3..];
        } else if rest.len() >= 9 && rest[..9].eq_ignore_ascii_case("<!doctype") {
            let Some(end) = rest.find('>') else {
                return false;
            };
            rest = &rest[end + 1..];
        } else {
            break;
        }
    }
    let Some(after) = rest.strip_prefix('<') else {
        return false;
    };
    let name_end = after
        .find(|character: char| character.is_whitespace() || character == '>' || character == '/')
        .unwrap_or(after.len());
    let name = &after[..name_end];
    let local = name.rsplit(':').next().unwrap_or(name);
    local == "svg"
}

fn base64_encode_into(bytes: &[u8], output: &mut String) {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let (chunks, remainder) = bytes.as_chunks::<3>();
    for chunk in chunks {
        let n = (u32::from(chunk[0]) << 16) | (u32::from(chunk[1]) << 8) | u32::from(chunk[2]);
        for shift in [18, 12, 6, 0] {
            output.push(ALPHABET[((n >> shift) & 63) as usize] as char);
        }
    }
    match remainder.len() {
        1 => {
            let n = u32::from(remainder[0]) << 16;
            output.push(ALPHABET[((n >> 18) & 63) as usize] as char);
            output.push(ALPHABET[((n >> 12) & 63) as usize] as char);
            output.push_str("==");
        }
        2 => {
            let n = (u32::from(remainder[0]) << 16) | (u32::from(remainder[1]) << 8);
            output.push(ALPHABET[((n >> 18) & 63) as usize] as char);
            output.push(ALPHABET[((n >> 12) & 63) as usize] as char);
            output.push(ALPHABET[((n >> 6) & 63) as usize] as char);
            output.push('=');
        }
        _ => {}
    }
}

const DOCUMENT_PREFIX: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<meta name="generator" content="MarkDev">
<meta name="referrer" content="no-referrer">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' data: file:; style-src 'unsafe-inline'; font-src data:; object-src 'none'; base-uri 'none'; form-action 'none'">
<title>"#;

/// Plain CSS that works in every current browser engine (Safari, Chrome,
/// Edge, Firefox) without script, fonts, or network access. Colours are
/// custom properties so the dark palette and print styles only swap values.
const DOCUMENT_MIDDLE: &str = r#"</title>
<style>
:root {
  color-scheme: light dark;
  --text: #1f2328; --muted: #59636e; --bg: #ffffff; --subtle: #f6f8fa;
  --border: #d1d9e0; --link: #0969da; --mark: #fff8c5; --accent: #b91c1c;
  --note: #0969da; --tip: #1a7f37; --important: #8250df; --warning: #9a6700; --caution: #cf222e;
  font: 17px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Helvetica, Arial, sans-serif;
  -webkit-text-size-adjust: 100%; text-size-adjust: 100%;
}
@media (prefers-color-scheme: dark) {
  :root {
    --text: #e6edf3; --muted: #9198a1; --bg: #0d1117; --subtle: #151b23;
    --border: #3d444d; --link: #4493f8; --mark: #bb800926; --accent: #f87171;
    --note: #4493f8; --tip: #3fb950; --important: #ab7df8; --warning: #d29922; --caution: #f85149;
  }
}
*, *::before, *::after { box-sizing: border-box; }
html { background: var(--bg); }
body { max-width: 780px; margin: 0 auto; padding: 3rem 1.5rem 5rem; color: var(--text); background: var(--bg); overflow-wrap: break-word; }
h1, h2, h3, h4, h5, h6 { position: relative; margin: 1.8em 0 .6em; line-height: 1.25; font-weight: 650; scroll-margin-top: 1rem; }
h1 { font-size: 2em; padding-bottom: .3em; border-bottom: 1px solid var(--border); }
h2 { font-size: 1.5em; padding-bottom: .3em; border-bottom: 1px solid var(--border); }
h3 { font-size: 1.25em; } h4 { font-size: 1em; } h5 { font-size: .9em; } h6 { font-size: .85em; color: var(--muted); }
main > :first-child { margin-top: 0; }
.anchor { margin-inline-start: .35em; color: var(--muted); text-decoration: none; font-weight: 400; opacity: 0; transition: opacity .15s; }
h1:hover .anchor, h2:hover .anchor, h3:hover .anchor, h4:hover .anchor, h5:hover .anchor, h6:hover .anchor, .anchor:focus { opacity: 1; }
p, ul, ol, dl, table, pre, blockquote, figure { margin: 0 0 1em; }
a { color: var(--link); text-underline-offset: .15em; }
a:not(:hover) { text-decoration: none; }
strong { font-weight: 650; }
mark { background: var(--mark); color: inherit; padding: 0 .15em; border-radius: 3px; }
del { color: var(--muted); }
hr { height: 1px; margin: 2em 0; border: 0; background: var(--border); }
ul, ol { padding-inline-start: 1.8em; }
li + li { margin-top: .25em; }
li > ul, li > ol { margin-bottom: 0; }
li:has(> input[type="checkbox"]) { list-style: none; margin-inline-start: -1.4em; }
input[type="checkbox"] { width: 1em; height: 1em; margin: 0 .45em 0 0; vertical-align: -.1em; accent-color: var(--accent); }
dt { font-weight: 650; margin-top: .6em; }
dd { margin-inline-start: 1.5em; }
pre, code, kbd, samp { font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace; }
code { font-size: .875em; padding: .15em .35em; border-radius: 6px; background: var(--subtle); }
pre { overflow-x: auto; padding: 1rem 1.1rem; border: 1px solid var(--border); border-radius: 10px; background: var(--subtle); line-height: 1.5; tab-size: 4; }
pre code { padding: 0; background: none; font-size: .85em; }
pre:has(> code[class*="language-"]) { position: relative; }
pre > code[class*="language-"]::before { position: absolute; top: .35rem; right: .6rem; color: var(--muted); font: 600 .68rem/1 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; letter-spacing: .04em; text-transform: uppercase; }
pre > code.language-mermaid::before { content: "Mermaid"; }
pre > code.language-math::before, pre > code.language-latex::before, pre > code.language-tex::before { content: "Math"; }
kbd { font-size: .8em; padding: .1em .4em; border: 1px solid var(--border); border-bottom-width: 2px; border-radius: 5px; background: var(--subtle); }
.math { font-family: math, "STIX Two Math", "Cambria Math", "Latin Modern Math", "Times New Roman", serif; }
.math-display { display: block; overflow-x: auto; margin: 1em 0; padding: .5em 0; text-align: center; font-size: 1.1em; }
blockquote { padding: .1em 1em; border-inline-start: 4px solid var(--border); color: var(--muted); }
blockquote > :last-child { margin-bottom: 0; }
blockquote[class^="markdown-alert-"] { color: var(--text); border-inline-start-color: var(--alert); }
blockquote[class^="markdown-alert-"]::before { display: block; margin: .5em 0 .35em; color: var(--alert); font-weight: 650; }
.markdown-alert-note { --alert: var(--note); } .markdown-alert-note::before { content: "Note"; }
.markdown-alert-tip { --alert: var(--tip); } .markdown-alert-tip::before { content: "Tip"; }
.markdown-alert-important { --alert: var(--important); } .markdown-alert-important::before { content: "Important"; }
.markdown-alert-warning { --alert: var(--warning); } .markdown-alert-warning::before { content: "Warning"; }
.markdown-alert-caution { --alert: var(--caution); } .markdown-alert-caution::before { content: "Caution"; }
table { display: block; width: max-content; max-width: 100%; overflow-x: auto; border-collapse: collapse; font-variant-numeric: tabular-nums; }
th, td { padding: .45rem .8rem; border: 1px solid var(--border); text-align: start; vertical-align: top; }
th { font-weight: 650; background: var(--subtle); }
tbody tr:nth-child(even) { background: color-mix(in srgb, var(--subtle) 60%, transparent); }
img { max-width: 100%; height: auto; border-radius: 4px; }
img[src$=".svg"], img[src^="data:image/svg+xml"] { border-radius: 0; }
sup { line-height: 0; }
.footnote-reference a { text-decoration: none; }
.footnote-definition { display: flex; align-items: baseline; gap: .5em; margin-top: .5em; font-size: .9em; color: var(--muted); }
.footnote-definition:first-of-type { margin-top: 2.5em; padding-top: 1em; border-top: 1px solid var(--border); }
.footnote-definition p { margin: 0; }
.footnote-definition-label { font-weight: 650; }
:target { scroll-margin-top: 1rem; }
.footnote-definition:target, h1:target, h2:target, h3:target, h4:target { background: var(--mark); }
@media (max-width: 600px) {
  :root { font-size: 16px; }
  body { padding: 1.5rem 1rem 3rem; }
  pre { margin-inline: -1rem; border-radius: 0; border-inline: 0; }
}
@media print {
  :root { --text: #000; --muted: #444; --bg: #fff; --subtle: #f5f5f5; --border: #bbb; --link: #000; font-size: 11pt; }
  body { max-width: none; padding: 0; }
  .anchor { display: none; }
  a[href^="http"]::after { content: " (" attr(href) ")"; font-size: .85em; color: var(--muted); overflow-wrap: anywhere; }
  pre { white-space: pre-wrap; }
  pre, blockquote, table, img, figure { break-inside: avoid; }
  h1, h2, h3, h4, h5, h6 { break-after: avoid; }
}
</style>
</head>
<body>
<main>
"#;

const DOCUMENT_SUFFIX: &str = "</main>\n</body>\n</html>\n";

#[cfg(test)]
mod tests {
    use super::BoundedHTMLWriter;
    use std::io::Write;

    #[test]
    fn bounded_writer_refuses_before_allocating_the_first_excess_byte() {
        let mut writer = BoundedHTMLWriter::new(4, 4);
        writer.write_all(b"1234").unwrap();
        assert!(writer.write_all(b"5").is_err());
        assert_eq!(writer.bytes, b"1234");
        assert_eq!(writer.attempted, 5);
    }
}
