//! Safe, standalone HTML export.
//!
//! Raw HTML is valid CommonMark, but an exported note is commonly opened in a
//! browser where passing it through would turn note text into executable code.
//! This renderer deliberately treats raw HTML as text, rejects active URL
//! schemes, and adds a closed Content Security Policy around the rendered
//! fragment.

use std::borrow::Cow;
use std::io::{self, Write};

use pulldown_cmark::{html, CowStr, Event, LinkType, Parser, Tag};

use crate::md::parse::options;

/// Rendering is linear but necessarily allocates output proportional to the
/// document. Refuse pathological inputs before duplicating them across the
/// Rust/Swift boundary.
pub const MAX_SOURCE_BYTES: usize = 16 * 1_048_576;
/// Titles normally come from a filesystem component (at most a few hundred
/// bytes), but the renderer is a public FFI boundary and must defend itself.
pub const MAX_TITLE_BYTES: usize = 8 * 1024;
const MAX_OUTPUT_BYTES: usize = 64 * 1024 * 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HTMLExportError {
    SourceTooLarge { actual: usize, maximum: usize },
    TitleTooLarge { actual: usize, maximum: usize },
    OutputTooLarge { actual: usize, maximum: usize },
}

/// Renders a complete browser-ready document from MarkDev's Markdown dialect.
pub fn render_document(source: &str, title: &str) -> Result<String, HTMLExportError> {
    if source.len() > MAX_SOURCE_BYTES {
        return Err(HTMLExportError::SourceTooLarge {
            actual: source.len(),
            maximum: MAX_SOURCE_BYTES,
        });
    }
    if title.len() > MAX_TITLE_BYTES {
        return Err(HTMLExportError::TitleTooLarge {
            actual: title.len(),
            maximum: MAX_TITLE_BYTES,
        });
    }

    // Keep output NUL-free even though Rust and Swift strings allow it. Avoid
    // copying the ordinary case; the replacement allocation is still bounded
    // by the source/title checks above.
    let clean_source: Cow<'_, str> = if source.contains('\0') {
        Cow::Owned(source.replace('\0', "\u{FFFD}"))
    } else {
        Cow::Borrowed(source)
    };
    let clean_title: Cow<'_, str> = if title.contains('\0') {
        Cow::Owned(title.replace('\0', "\u{FFFD}"))
    } else {
        Cow::Borrowed(title)
    };

    // Render straight into a writer that refuses the first byte beyond the
    // ceiling. Checking a String after `push_html` returns is too late: the
    // pathological allocation has already happened by then.
    let initial_capacity = clean_source
        .len()
        .saturating_add(clean_title.len())
        .saturating_add(4 * 1024)
        .min(MAX_OUTPUT_BYTES);
    let mut output = BoundedHTMLWriter::new(MAX_OUTPUT_BYTES, initial_capacity);
    output
        .write_all(DOCUMENT_PREFIX.as_bytes())
        .map_err(|_| output.error())?;
    html::write_html_io(
        &mut output,
        std::iter::once(Event::Text(CowStr::Borrowed(clean_title.as_ref()))),
    )
    .map_err(|_| output.error())?;
    output
        .write_all(DOCUMENT_MIDDLE.as_bytes())
        .map_err(|_| output.error())?;
    let events = Parser::new_ext(clean_source.as_ref(), options()).map(sanitize_event);
    html::write_html_io(&mut output, events).map_err(|_| output.error())?;
    output
        .write_all(DOCUMENT_SUFFIX.as_bytes())
        .map_err(|_| output.error())?;

    // Every input to the writer is UTF-8 text generated by pulldown-cmark.
    Ok(String::from_utf8(output.into_bytes()).expect("HTML writer emitted invalid UTF-8"))
}

/// A hard allocation boundary around pulldown-cmark's streaming renderer.
struct BoundedHTMLWriter {
    bytes: Vec<u8>,
    maximum: usize,
    attempted: usize,
}

impl BoundedHTMLWriter {
    fn new(maximum: usize, initial_capacity: usize) -> Self {
        Self {
            bytes: Vec::with_capacity(initial_capacity.min(maximum)),
            maximum,
            attempted: 0,
        }
    }

    fn error(&self) -> HTMLExportError {
        HTMLExportError::OutputTooLarge {
            actual: self.attempted.max(self.maximum.saturating_add(1)),
            maximum: self.maximum,
        }
    }

    fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }
}

impl Write for BoundedHTMLWriter {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        self.attempted = self.bytes.len().saturating_add(buffer.len());
        if self.attempted > self.maximum {
            return Err(io::Error::new(
                io::ErrorKind::FileTooLarge,
                "rendered HTML exceeds its byte limit",
            ));
        }
        self.bytes.extend_from_slice(buffer);
        Ok(buffer.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

fn sanitize_event(event: Event<'_>) -> Event<'_> {
    match event {
        // Preserve what the author typed, but never interpret it in the
        // browser. `push_html` escapes Text events for us.
        Event::Html(value) | Event::InlineHtml(value) => Event::Text(value),
        Event::Start(Tag::Link {
            link_type,
            dest_url,
            title,
            id,
        }) => Event::Start(Tag::Link {
            dest_url: sanitize_destination(dest_url, true, link_type),
            link_type,
            title,
            id,
        }),
        Event::Start(Tag::Image {
            link_type,
            dest_url,
            title,
            id,
        }) => Event::Start(Tag::Image {
            // MarkDev's preview does not fetch remote images. Export keeps the
            // same privacy boundary rather than creating a browser beacon.
            dest_url: sanitize_destination(dest_url, false, link_type),
            link_type,
            title,
            id,
        }),
        other => other,
    }
}

fn sanitize_destination<'a>(
    destination: CowStr<'a>,
    allow_remote: bool,
    link_type: LinkType,
) -> CowStr<'a> {
    if link_type == LinkType::Email {
        return destination;
    }

    let compact: String = destination
        .chars()
        .filter(|character| !character.is_ascii_control() && !character.is_ascii_whitespace())
        .collect();
    let lower = compact.to_ascii_lowercase();

    // Protocol-relative image URLs also perform a network request. Links may
    // navigate there only after an explicit click.
    if !allow_remote && lower.starts_with("//") {
        return CowStr::Borrowed("#");
    }

    let scheme = lower.find(':').and_then(|colon| {
        let boundary = lower.find(['/', '?', '#']).unwrap_or(usize::MAX);
        (colon < boundary).then_some(&lower[..colon])
    });

    let allowed = match scheme {
        None => true,
        Some("http" | "https") => allow_remote,
        Some("mailto" | "file") => true,
        _ => false,
    };
    if allowed {
        destination
    } else {
        CowStr::Borrowed("#")
    }
}

const DOCUMENT_PREFIX: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="referrer" content="no-referrer">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' data: file:; style-src 'unsafe-inline'; font-src data:; object-src 'none'; base-uri 'none'; form-action 'none'">
<title>"#;

const DOCUMENT_MIDDLE: &str = r#"</title>
<style>
:root { color-scheme: light dark; font: 17px/1.6 -apple-system, BlinkMacSystemFont, sans-serif; }
body { max-width: 760px; margin: 3rem auto; padding: 0 1.5rem 4rem; color: CanvasText; background: Canvas; }
pre, code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
pre { overflow-x: auto; padding: 1rem; border-radius: 10px; background: color-mix(in srgb, CanvasText 7%, Canvas); }
code { font-size: .9em; }
blockquote { margin-inline: 0; padding-inline: 1rem; border-inline-start: 3px solid GrayText; color: GrayText; }
table { width: 100%; border-collapse: collapse; }
th, td { padding: .45rem .65rem; border: 1px solid color-mix(in srgb, CanvasText 20%, Canvas); text-align: start; }
img { max-width: 100%; height: auto; }
a { color: LinkText; }
</style>
</head>
<body>
<main>
"#;

const DOCUMENT_SUFFIX: &str = "</main>\n</body>\n</html>\n";

#[cfg(test)]
mod tests {
    use super::BoundedHTMLWriter;
    use std::io::Write;

    #[test]
    fn bounded_writer_refuses_before_allocating_the_first_excess_byte() {
        let mut writer = BoundedHTMLWriter::new(4, 4);
        writer.write_all(b"1234").unwrap();
        assert!(writer.write_all(b"5").is_err());
        assert_eq!(writer.bytes, b"1234");
        assert_eq!(writer.attempted, 5);
    }
}
